# Generated by Django 4.0.3 on 2022-12-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sports',
            new_name='Sport',
        ),
    ]
